// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REFERENCIAPARTE1.Models;

#nullable disable

namespace referenciaPARTE1.Migrations
{
    [DbContext(typeof(LivrosContext))]
    partial class LivrosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("REFERENCIAPARTE1.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorLivro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMaterial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloLivro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
